#!/command/with-contenv bash
# shellcheck shell=bash

initial_prompt_args=()
if [ -n "${WHISPER_INITIAL_PROMPT:-}" ]; then
    initial_prompt_args+=(--initial-prompt "${WHISPER_INITIAL_PROMPT}")
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 10300" \
        s6-setuidgid abc python3 -m wyoming_faster_whisper \
        --uri 'tcp://0.0.0.0:10300' \
        --model "${WHISPER_MODEL:-auto}" \
        --beam-size "${WHISPER_BEAM:-1}" \
        --language "${WHISPER_LANG:-auto}" \
        --data-dir /config \
        --download-dir /config \
        ${DEBUG:+--debug} \
        ${LOCAL_ONLY:+--local-files-only} \
        "${initial_prompt_args[@]}"
